{{- if .Values.verticalPodAutoscaler.enabled }}
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: {{ include "admin.fullname" . }}
  labels:
    {{- include "admin.labels" . | nindent 4 }}
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "admin.fullname" . }}
  updatePolicy:
    updateMode: {{ .Values.verticalPodAutoscaler.updateMode | quote }}
  resourcePolicy:
    containerPolicies:
    - containerName: {{ .Chart.Name }}
      {{- if .Values.verticalPodAutoscaler.controlledResources }}
      controlledResources:
        {{- toYaml .Values.verticalPodAutoscaler.controlledResources | nindent 8 }}
      {{- end }}
      {{- if .Values.verticalPodAutoscaler.minAllowed }}
      minAllowed:
        {{- toYaml .Values.verticalPodAutoscaler.minAllowed | nindent 8 }}
      {{- end }}
      {{- if .Values.verticalPodAutoscaler.maxAllowed }}
      maxAllowed:
        {{- toYaml .Values.verticalPodAutoscaler.maxAllowed | nindent 8 }}
      {{- end }}
{{- end }}
