apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: api
  name:  api
  namespace: notification-canada-ca
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      initContainers:
        - name: init-postgres
          image: alpine
          command:
            [
              "sh",
              "-c",
              "until nslookup $(POSTGRES_HOST); do echo waiting for postgres; sleep 2; done;",
            ]
        - name: migrate-db
          image: api
          env:
            - name: ADMIN_BASE_URL
              value: https://$(BASE_DOMAIN)
            - name: ADMIN_CLIENT_SECRET
              value: '$(ADMIN_CLIENT_SECRET)'
            - name: ASSET_UPLOAD_BUCKET_NAME
              value: '$(ASSET_UPLOAD_BUCKET_NAME)'
            - name: ASSET_DOMAIN
              value: '$(ASSET_DOMAIN)'
            - name: AWS_ROUTE53_ZONE
              value: '$(AWS_ROUTE53_ZONE)'
            - name: AWS_SES_REGION
              value: '$(AWS_SES_REGION)'
            - name: AWS_SES_SMTP
              value: '$(AWS_SES_SMTP)'
            - name: AWS_SES_ACCESS_KEY
              value: '$(AWS_SES_ACCESS_KEY)'
            - name: AWS_SES_SECRET_KEY
              value: '$(AWS_SES_SECRET_KEY)'
            - name: BATCH_INSERTION_CHUNK_SIZE
              value: '$(BATCH_INSERTION_CHUNK_SIZE)'
            - name: BULK_SEND_TEST_SERVICE_ID
              value: '$(BULK_SEND_TEST_SERVICE_ID)'
            - name: CSV_UPLOAD_BUCKET_NAME
              value: '$(CSV_UPLOAD_BUCKET_NAME)'
            - name: DANGEROUS_SALT
              value: '$(DANGEROUS_SALT)'
            - name: DOCUMENT_DOWNLOAD_API_HOST
              value: 'http://document-download-api.notification-canada-ca.svc.cluster.local:7000'
            - name: DOCUMENTATION_DOMAIN
              value: 'documentation.$(BASE_DOMAIN)'
            - name: FF_SALESFORCE_CONTACT
              value: '$(FF_SALESFORCE_CONTACT)'
            - name: FF_SPIKE_SMS_DAILY_LIMIT
              value: '$(FF_SPIKE_SMS_DAILY_LIMIT)'
            - name: FF_SMS_PARTS_UI
              value: '$(FF_SMS_PARTS_UI)'
            - name: FIDO2_DOMAIN
              value: '$(FIDO2_DOMAIN)'
            - name: FLASK_APP
              value: application.py
            - name: NOTIFY_EMAIL_DOMAIN
              value: '$(BASE_DOMAIN)'
            - name: NOTIFY_ENVIRONMENT
              value: '$(ENVIRONMENT)'
            - name: NOTIFICATION_QUEUE_PREFIX
              value: 'eks-notification-canada-ca'
            - name: REDIS_URL
              value: '$(REDIS_URL)'
            - name: REDIS_PUBLISH_URL
              value: '$(REDIS_PUBLISH_URL)'
            - name: REDIS_ENABLED
              value: '1'
            - name: SALESFORCE_DOMAIN
              value: '$(SALESFORCE_DOMAIN)'
            - name: SALESFORCE_ENGAGEMENT_PRODUCT_ID
              value: '$(SALESFORCE_ENGAGEMENT_PRODUCT_ID)'
            - name: SALESFORCE_ENGAGEMENT_RECORD_TYPE
              value: '$(SALESFORCE_ENGAGEMENT_RECORD_TYPE)'
            - name: SALESFORCE_ENGAGEMENT_STANDARD_PRICEBOOK_ID
              value: '$(SALESFORCE_ENGAGEMENT_STANDARD_PRICEBOOK_ID)'
            - name: SALESFORCE_GENERIC_ACCOUNT_ID
              value: '$(SALESFORCE_GENERIC_ACCOUNT_ID)'
            - name: SALESFORCE_PASSWORD
              value: '$(SALESFORCE_PASSWORD)'
            - name: SALESFORCE_SECURITY_TOKEN
              value: '$(SALESFORCE_SECURITY_TOKEN)'
            - name: SALESFORCE_USERNAME
              value: '$(SALESFORCE_USERNAME)'
            - name: SECRET_KEY
              value: '$(SECRET_KEY)'
            - name: SENDGRID_API_KEY
              value: '$(SENDGRID_API_KEY)'
            - name: SQLALCHEMY_DATABASE_URI
              value: '$(POSTGRES_SQL)'
            - name: STATSD_HOST
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: TWILIO_ACCOUNT_SID
              value: '$(TWILIO_ACCOUNT_SID)'
            - name: TWILIO_AUTH_TOKEN
              value: '$(TWILIO_AUTH_TOKEN)'
            - name: TWILIO_FROM_NUMBER
              value: '$(TWILIO_FROM_NUMBER)'
            - name: AWS_US_TOLL_FREE_NUMBER
              value: '$(AWS_US_TOLL_FREE_NUMBER)'
            - name: NEW_RELIC_MONITOR_MODE
              value: '$(NEW_RELIC_MONITOR_MODE)'
            - name: ZENDESK_SELL_API_URL
              value: '$(ZENDESK_SELL_API_URL)'
            - name: ZENDESK_SELL_API_KEY
              value: '$(ZENDESK_SELL_API_KEY)'
            - name: ZENDESK_API_URL
              value: '$(ZENDESK_API_URL)'
            - name: ZENDESK_API_KEY
              value: '$(ZENDESK_API_KEY)'
          command:
            [
              "sh",
              "-c",
              "flask db upgrade",
            ]
      containers:
        - image: api
          imagePullPolicy: Always
          name: api
          env:
            - name: ADMIN_BASE_URL
              value: https://$(BASE_DOMAIN)
            - name: ADMIN_CLIENT_SECRET
              value: '$(ADMIN_CLIENT_SECRET)'
            - name: ALLOW_HTML_SERVICE_IDS
              value: '$(ALLOW_HTML_SERVICE_IDS)'
            - name: API_HOST_NAME
              value: '$(API_HOST_NAME)'
            - name: ASSET_UPLOAD_BUCKET_NAME
              value: '$(ASSET_UPLOAD_BUCKET_NAME)'
            - name: ASSET_DOMAIN
              value: '$(ASSET_DOMAIN)'
            - name: AWS_PINPOINT_REGION
              value: '$(AWS_PINPOINT_REGION)'
            - name: AWS_REGION
              value: '$(AWS_REGION)'
            - name: AWS_ROUTE53_ZONE
              value: '$(AWS_ROUTE53_ZONE)'
            - name: AWS_SES_REGION
              value: '$(AWS_SES_REGION)'
            - name: AWS_SES_SMTP
              value: '$(AWS_SES_SMTP)'
            - name: AWS_SES_ACCESS_KEY
              value: '$(AWS_SES_ACCESS_KEY)'
            - name: AWS_SES_SECRET_KEY
              value: '$(AWS_SES_SECRET_KEY)'
            - name: BATCH_INSERTION_CHUNK_SIZE
              value: '$(BATCH_INSERTION_CHUNK_SIZE)'
            - name: CSV_UPLOAD_BUCKET_NAME
              value: '$(CSV_UPLOAD_BUCKET_NAME)'
            - name: DANGEROUS_SALT
              value: '$(DANGEROUS_SALT)'
            - name: DOCUMENT_DOWNLOAD_API_HOST
              value: 'http://document-download-api.notification-canada-ca.svc.cluster.local:7000'
            - name: FF_SALESFORCE_CONTACT
              value: '$(FF_SALESFORCE_CONTACT)'
            - name: FF_SPIKE_SMS_DAILY_LIMIT
              value: '$(FF_SPIKE_SMS_DAILY_LIMIT)'
            - name: FIDO2_DOMAIN
              value: '$(FIDO2_DOMAIN)'
            - name: FRESH_DESK_API_URL
              value: '$(FRESH_DESK_API_URL)'
            - name: FRESH_DESK_API_KEY
              value: '$(FRESH_DESK_API_KEY)'
            - name: FRESH_DESK_PRODUCT_ID
              value: '$(FRESH_DESK_PRODUCT_ID)'
            - name: HC_EN_SERVICE_ID
              value: '$(HC_EN_SERVICE_ID)'
            - name: HC_FR_SERVICE_ID
              value: '$(HC_FR_SERVICE_ID)'
            - name: NOTIFY_EMAIL_DOMAIN
              value: '$(BASE_DOMAIN)'
            - name: NOTIFY_ENVIRONMENT
              value: '$(ENVIRONMENT)'
            - name: NOTIFICATION_QUEUE_PREFIX
              value: 'eks-notification-canada-ca'
            - name: REDIS_URL
              value: '$(REDIS_URL)'
            - name: REDIS_PUBLISH_URL
              value: '$(REDIS_PUBLISH_URL)'
            - name: REDIS_ENABLED
              value: '1'
            - name: SALESFORCE_DOMAIN
              value: '$(SALESFORCE_DOMAIN)'
            - name: SALESFORCE_ENGAGEMENT_PRODUCT_ID
              value: '$(SALESFORCE_ENGAGEMENT_PRODUCT_ID)'
            - name: SALESFORCE_ENGAGEMENT_RECORD_TYPE
              value: '$(SALESFORCE_ENGAGEMENT_RECORD_TYPE)'
            - name: SALESFORCE_ENGAGEMENT_STANDARD_PRICEBOOK_ID
              value: '$(SALESFORCE_ENGAGEMENT_STANDARD_PRICEBOOK_ID)'
            - name: SALESFORCE_GENERIC_ACCOUNT_ID
              value: '$(SALESFORCE_GENERIC_ACCOUNT_ID)'
            - name: SALESFORCE_PASSWORD
              value: '$(SALESFORCE_PASSWORD)'
            - name: SALESFORCE_SECURITY_TOKEN
              value: '$(SALESFORCE_SECURITY_TOKEN)'
            - name: SALESFORCE_USERNAME
              value: '$(SALESFORCE_USERNAME)'
            - name: SECRET_KEY
              value: '$(SECRET_KEY)'
            - name: SENDGRID_API_KEY
              value: '$(SENDGRID_API_KEY)'
            - name: SQLALCHEMY_DATABASE_URI
              value: '$(POSTGRES_SQL)'
            - name: SQLALCHEMY_DATABASE_READER_URI
              value: '$(SQLALCHEMY_DATABASE_READER_URI)'
            - name: SQLALCHEMY_POOL_SIZE
              value: '$(SQLALCHEMY_POOL_SIZE)'
            - name: STATSD_HOST
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: TWILIO_ACCOUNT_SID
              value: '$(TWILIO_ACCOUNT_SID)'
            - name: TWILIO_AUTH_TOKEN
              value: '$(TWILIO_AUTH_TOKEN)'
            - name: TWILIO_FROM_NUMBER
              value: '$(TWILIO_FROM_NUMBER)'
            - name: AWS_US_TOLL_FREE_NUMBER
              value: '$(AWS_US_TOLL_FREE_NUMBER)'
            - name: SENTRY_URL
              value: '$(SENTRY_URL)'
            - name: NEW_RELIC_APP_NAME
              value: 'notification-api-$(ENVIRONMENT)'
            - name: NEW_RELIC_DISTRIBUTED_TRACING_ENABLED
              value: 'true'
            - name: NEW_RELIC_LICENSE_KEY
              value: '$(NEW_RELIC_LICENSE_KEY)'
            - name: NEW_RELIC_MONITOR_MODE
              value: '$(NEW_RELIC_MONITOR_MODE)'
            - name: ZENDESK_SELL_API_URL
              value: 'https://api.getbase.com'
            - name: ZENDESK_SELL_API_KEY
              value: '$(ZENDESK_SELL_API_KEY)'
            - name: ZENDESK_API_URL
              value: '$(ZENDESK_API_URL)'
            - name: ZENDESK_API_KEY
              value: '$(ZENDESK_API_KEY)'
            - name: FF_CLOUDWATCH_METRICS_ENABLED
              value: 'True'
          resources:
            requests:
              cpu: "400m"
              memory: "700Mi"
            limits:
              cpu: "1200m"
              memory: "900Mi"
          ports:
            - containerPort: 6011
          readinessProbe:
            httpGet:
              path: /_status?simple=true
              port: 6011
            initialDelaySeconds: 10
            periodSeconds: 3
            timeoutSeconds: 1
            successThreshold: 3
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: "/_status?simple=true"
              port: 6011
            initialDelaySeconds: 30
            periodSeconds: 3
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 3
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
