name: AI Code Review

on:
  push:
    branches-ignore:
      - main

jobs:
  ai_code_review:
    if: contains(github.event.head_commit.message, '[review]')
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0

    - name: AI Code Review
      uses: cds-snc/cds-ai-codereviewer@main
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        OPENAI_API_MODEL: ${{ vars.OPENAI_API_MODEL }}
        OPENAI_API_VERSION: ${{ vars.OPENAI_API_VERSION }}
        OPENAI_BASE_URL: ${{ vars.OPENAI_BASE_URL }}
        exclude: "**/.env,**/*.aws,**/*.zip,*lock*"
        include: "**/*.js,**/*.md,**/*.ps1,**/*.sh,**/*.txt,**/*.yml"
